name: Push Public Image to Amazon ECR

on:
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull public Docker image
        run: docker pull unknown102/my-classifier-image

      - name: Tag image for ECR
        run: |
          IMAGE_NAME=my-classifier-image
          docker tag unknown102/my-classifier-image 183295451913.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:latest

      - name: Create ECR repo if not exists
        run: |
          aws ecr create-repository --repository-name my-classifier-image --region us-east-1 || true

      - name: Push image to ECR
        run: |
          IMAGE_NAME=my-classifier-image
          docker push 183295451913.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:latest
