name: Push Public Image to Amazon ECR

on:
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull public Docker image
        run: docker pull asimayub747/frontend-image-test1

      - name: Tag image for ECR
        run: |
          IMAGE_NAME=frontend-image-test1
          docker tag asimayub747/frontend-image-test1 183295451913.dkr.ecr.ap-south-1.amazonaws.com/$IMAGE_NAME:latest

      - name: Create ECR repo if not exists
        run: |
          aws ecr create-repository --repository-name frontend-image-test1 --region ap-south-1 || true

      - name: Push image to ECR
        run: |
          IMAGE_NAME=frontend-image-test1
          docker push 183295451913.dkr.ecr.ap-south-1.amazonaws.com/$IMAGE_NAME:latest
